recipe/main/urls.py
from django.urls import path
from .views import index, other_page, RSLoginView, profile, RSLogoutView
from .views import ChangeUserInfoView, RSPasswordChangeView, detail, profile_rs_detail
from .views import RegisterUserView, RegisterDoneView, DeleteUserView, by_category
from .views import profile_rs_add, profile_rs_change, profile_rs_delete, all_recipes
from .views import all_recipes_detail

app_name = 'main'
urlpatterns = [
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', RSLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', RSPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change/<int:pk>/', profile_rs_change, name='profile_rs_change'),
    path('accounts/profile/delete/<int:pk>/', profile_rs_delete, name='profile_rs_delete'),
    path('accounts/profile/add/', profile_rs_add, name='profile_rs_add'),
    path('accounts/profile/<int:pk>/', profile_rs_detail, name='profile_rs_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', RSLoginView.as_view(), name='login'),
    path('all_recipes/<int:pk>/', all_recipes_detail, name='all_recipes_detail'),
    path('all_recipes/', all_recipes, name='all_recipes'),
    path('<int:category_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_category, name='by_category'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

recipe/recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.views import serve
# from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns.append(path('static/<path:path>', never_cache(serve)))

recipe/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utilities import get_timestamp_path

class AdvUser(AbstractUser):
    send_messages = models.BooleanField(default=False, verbose_name='Следить за новыми рецептами?')

    def delete(self, *args, **kwargs):
        for rs in self.rs_set.all():
            rs.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass

class Category(models.Model):
    name = models.CharField(max_length=20, db_index=True, unique=True, verbose_name='Название')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Порядок')

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('order', 'name')
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Rs(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    title = models.CharField(max_length=40, verbose_name='Название')
    description = models.TextField(default='', verbose_name='Описание')
    cooking_steps = models.TextField(blank=True,default='', verbose_name='Шаги приготовления')
    cooking_time = models.PositiveIntegerField(default=1, verbose_name='Время приготовления в минутах')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Автор рецепта')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлено')

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ['-created_at']

recipe/main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import AdvUser, Rs


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput, help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1
    
    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        if commit:
            user.save()
        return user
    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')

class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')

class RsForm(forms.ModelForm):
    class Meta:
        model = Rs
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

recipe/main/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.base import TemplateView
from django.contrib import messages
from django.core.paginator import Paginator
from .models import AdvUser, Category, Rs
from .forms import ChangeUserInfoForm, RegisterUserForm
from .forms import SearchForm, RsForm

class RSLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'

class RSLoginView(LoginView):
    template_name = 'main/login.html'

def by_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    rss = Rs.objects.filter(category=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(description__icontains=keyword)
        rss = rss.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword':keyword})
    paginator = Paginator(rss, 5)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'category': category, 'page': page, 'rss': page.object_list, 'form': form}
    return render(request, 'main/by_category.html', context)


def other_page(request,page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

def index(request):
    no_random = False
    rss = []
    if request.user.is_authenticated:
        adv_user = AdvUser.objects.get(pk=request.user.pk)
        no_random = adv_user.send_messages
    if no_random:
        rss = Rs.objects.all()[:5]
    else:
        rss = Rs.objects.all().order_by('?')[:5]
    context = {'rss': rss, 'no_random': no_random}
    return render(request,'main/index.html', context)

@login_required
def profile(request):
    rss = Rs.objects.filter(author=request.user.pk)
    context = {'rss': rss}
    return render(request, 'main/profile.html', context)

class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class RSPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'

class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')

class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'

class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    
    def post(self,request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

def detail(request, category_pk, pk):
    rs = get_object_or_404(Rs, pk=pk)
    context = {'rs': rs}
    return render(request, 'main/detail.html', context)

@login_required
def profile_rs_detail(request, pk):
    rs = get_object_or_404(Rs, pk=pk)
    context = {'rs': rs}
    return render(request, 'main/profile_rs_detail.html', context)

@login_required
def profile_rs_add(request):
    if request.method == 'POST':
        form = RsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Рецепт добавлен')
            return redirect('main:profile')
    else:
        form = RsForm(initial={'author': request.user.pk})
    context = {'form': form}
    return render(request, 'main/profile_rs_add.html', context)

@login_required
def profile_rs_change(request, pk):
    rs = get_object_or_404(Rs, pk=pk)
    if request.method == 'POST':
        form = RsForm(request.POST, request.FILES, instance=rs)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Рецепт изменен')
            return redirect('main:profile')
    else:
        form = RsForm(instance=rs)
    context = {'form': form}
    return render(request, 'main/profile_rs_change.html', context) 

@login_required
def profile_rs_delete(request, pk):
    rs = get_object_or_404(Rs, pk=pk)
    if request.method == 'POST':
        rs.delete()
        messages.add_message(request, messages.SUCCESS, 'Рецепт удален')
        return redirect('main:profile')
    else:
        context = {'rs': rs}
        return render(request, 'main/profile_rs_delete.html', context) 

def all_recipes(request):
    rss = Rs.objects.all()
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(description__icontains=keyword)
        rss = rss.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword':keyword})
    paginator = Paginator(rss, 5)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'page': page, 'rss': page.object_list, 'form': form}
    return render(request, 'main/all_recipes.html', context)

def all_recipes_detail(request, pk):
    rs = get_object_or_404(Rs, pk=pk)
    context = {'rs': rs}
    return render(request, 'main/all_recipes_detail.html', context)

recipe/main/templates/main/about.html
{% extends 'base.html' %}
{% block title %}O сайте{% endblock %}
{% block content %}
<h2>О сайте</h2>
<p>Сайт, на котором пользователи могут добавлять свои рецепты блюд и просматривать рецепты других пользователей.</p>
{% endblock %}

recipe/main/templates/main/all_recipes.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Все рецепты{% endblock %}
{% block content %}
<h2 class="mb-2">Все рецепты</h2>
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Искать' button_type='submit' %}
        </form>
    </div>
</div>
{% if rss %}
<ul class="list-unstyled">
    {% for rs in rss %}
    <li class="media my-5 p-3 border">
        {% url 'main:all_recipes_detail' pk=rs.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if rs.image %}
            <img class="mr-3" src="{% thumbnail rs.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.jpg' %}">
            {% endif %}
        </a>
        <div>
            <h4><a href="{% url 'main:by_category' pk=rs.category.pk %}">{{ rs.category.name }}</a></h4>
            <h3><a href="{{ url }}{{ all }}">{{ rs.title }}</a></h3>
            <div>{{ rs.description }}</div>
            <p class="text-right font-weight-bold">{{ rs.cooking_time }} мин.</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

recipe/main/templates/main/by_category.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}
{% block title %}{{ category }}{% endblock %}
{% block content %}
<h2 class="mb-2">{{ category }}</h2>
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Искать' button_type='submit' %}
        </form>
    </div>
</div>
{% if rss %}
<ul class="list-unstyled">
    {% for rs in rss %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' category_pk=category.pk pk=rs.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if rs.image %}
            <img class="mr-3" src="{% thumbnail rs.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.jpg' %}">
            {% endif %}
        </a>
        <div>
            <h3><a href="{{ url }}{{ all }}">{{ rs.title }}</a></h3>
            <div>{{ rs.description }}</div>
            <p class="text-right font-weight-bold">{{ rs.cooking_time }} мин.</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

recipe/main/templates/main/change_user_info.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Правка личных данных{% endblock %}
{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

recipe/main/templates/main/delete_user.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Удаление пользователя{% endblock %}
{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

recipe/main/templates/main/detail.html
{% extends 'base.html' %}
{% block title %}{{ rs.title }} - {{ rs.category.name }}{% endblock %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if rs.image %}
        <div class="col-md-auto">
            <img class="main-image" src="{{ rs.image.url}}">
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ rs.title }}</h2>
            <p>{{ rs.description }}</p>
            <p>{{ rs.cooking_steps }}</p>
            <p>{{ rs.cooking_steps }}</p>
            <p class="font-weight-bold">{{ rs.cooking_time }} мин.</p>
            <p class="text-right font-italic">Добавлено {{ rs.created_at }}</p>
        </div>
    </div>
</div>
<p><a href="{% url 'main:by_category' pk=rs.category.pk %}{{ all }}">Назад</a></p>
{% endblock %}

recipe/main/templates/main/index.html
{% extends 'base.html' %}
{% block content %}
<h2>5 случайных рецептов кратко</h2>
{% endblock %}

recipe/main/templates/main/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Вход{% endblock %}
{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit='Войти' %}{% endbuttons %}
</form>
{% endif %}
{% endblock %}

recipe/main/templates/main/logout.html
{% extends 'base.html' %}
{% block title %}Выход{% endblock %}
{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

recipe/main/templates/main/password_change.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сменить пароль' %}{% endbuttons %}
</form>
{% endblock %}

recipe/main/templates/main/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Профиль пользователя{% endblock %}
{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<h3>Ваши рецепты</h3>
{% if rss %}
<ul class="list-unstyled">
    {% for rs in rss %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_rs_detail' pk=rs.pk as url %}
        <a href="{{ url }}">
            {% if rs.image %}
            <img class="mr-3" src="{% thumbnail rs.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.jpg' %}">
            {% endif %}
        </a>
        <div>
            <h3><a href="{{ url }}">{{ rs.title }}</a></h3>
            <div>{{ rs.description }}</div>
            <p class="font-weight-bold">Время приготовления: {{ rs.cooking_time }} мин.</p>
            <p class="text-right mt-2">
                <a href="{% url 'main:profile_rs_change' pk=rs.pk %}">Изменить</a>
                <a href="{% url 'main:profile_rs_delete' pk=rs.pk %}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
<p><a href="{% url 'main:profile_rs_add' %}">Добавить рецепт</a></p>
{% endblock %}

recipe/main/templates/main/profile_rs_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Добавление рецепта - Профиль пользователя{% endblock %}
{% block content %}
<h2>Добавление рецепта</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

recipe/main/templates/main/profile_rs_detail.html
{% extends 'base.html' %}
{% block title %}{{ rs.title }} - {{ rs.category.name }}{% endblock %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if rs.image %}
        <div class="col-md-auto">
            <img class="main-image" src="{{ rs.image.url}}">
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ rs.title }}</h2>
            <p>{{ rs.description }}</p>
            <p>{{ rs.cooking_steps }}</p>
            <p class="font-weight-bold">{{ rs.cooking_time }} мин.</p>
            <p class="text-right font-italic">Добавлено {{ rs.created_at }}</p>
        </div>
    </div>
</div>
<p><a href="{% url 'main:profile' %}">Назад</a></p>
{% endblock %}

recipe/main/templates/main/register_done.html
{% extends 'base.html' %}
{% block title %}Регистрация завершена{% endblock %}
{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
{% endblock %}