recipe/main/urls.py
from django.urls import path
from .views import index, other_page, RSLoginView, profile, RSLogoutView
from .views import ChangeUserInfoView, RSPasswordChangeView, detail, profile_rs_detail
from .views import RegisterUserView, RegisterDoneView, DeleteUserView, by_category
from .views import profile_rs_add, profile_rs_change, profile_rs_delete, all_recipes
from .views import all_recipes_detail

app_name = 'main'
urlpatterns = [
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', RSLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', RSPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change/<int:pk>/', profile_rs_change, name='profile_rs_change'),
    path('accounts/profile/delete/<int:pk>/', profile_rs_delete, name='profile_rs_delete'),
    path('accounts/profile/add/', profile_rs_add, name='profile_rs_add'),
    path('accounts/profile/<int:pk>/', profile_rs_detail, name='profile_rs_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', RSLoginView.as_view(), name='login'),
    path('all_recipes/<int:pk>/', all_recipes_detail, name='all_recipes_detail'),
    path('all_recipes/', all_recipes, name='all_recipes'),
    path('<int:category_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_category, name='by_category'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

recipe/recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.views import serve
# from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns.append(path('static/<path:path>', never_cache(serve)))

recipe/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
  <link rel="shortcut icon" href="{% static 'main/favicon.ico' %}" type="image/x-icon">
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}Главная{% endblock %} - Сайт рецептов</title>
  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
  {% bootstrap_javascript jquery='slim' %}
</head>

<body class="container-fluid">
  <header class="mb-4">
    <h1 class="display-1 text-center">
      <a class="nav-link" href="{% url 'main:all_recipes' %}">Рецепты</a>
    </h1>
  </header>
  <div class="row">

    <ul class="col nav justify-content border">
      <li class="nav-item"><a class="nav-link" href="{% url 'main:index' %}">Главная</a></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
          aria-expanded="false">Категория</a>
        <div class="dropdown-menu">
          {% for category in categories %}
          <a class="dropdown-item" href="{% url 'main:by_category' pk=category.pk %}">{{ category.name }}</a>
          {% endfor %}
        </div>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
          aria-expanded="false">Пpoфиль</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'main:profile' %}">Moи рецепты</a>
          <a class="dropdown-item" href="{% url 'main:profile_change' %}">Изменить личные данные</a>
          <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить пароль</a>
          <div class="dropdown-divider"></div>
          <form action="{% url 'main:logout' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Выйти</button>
          </form>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Удалить</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Bxoд</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'main:register' %}">Регистрация</a></li>
      {% endif %}
      <li class="nav-item"><a class="nav-link" href="{% url 'main:other' page='about' %}">О сайте</a></li>
    </ul>
  </div>
  <section class="border ру-2">
    {% bootstrap_messages %}
    {% block content %}
    <p>Скоро тут появится текст...</p>
    {% endblock %}
  </section>
  <footer class="mt-3">
    <p class="text-right font-italic">&copy;2024 Павел Поздняков.</p>
  </footer>
</body>

</html>